// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC5N23TZp-uKGZWsQeIf5bT1cAONAFPoRo',
    appId: '1:892907522158:web:6b96a463624bc87dee7e7f',
    messagingSenderId: '892907522158',
    projectId: 'smartsproutadmin',
    authDomain: 'smartsproutadmin.firebaseapp.com',
    storageBucket: 'smartsproutadmin.firebasestorage.app',
    measurementId: 'G-N7C4S38P6W',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyANlBxYFTPv0t7_RuGlRApt_aCtI8M-s44',
    appId: '1:892907522158:android:3682672edc0b1982ee7e7f',
    messagingSenderId: '892907522158',
    projectId: 'smartsproutadmin',
    storageBucket: 'smartsproutadmin.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBDzZUgozsBsRQ8K--dtMur5Cz4s1Zr1f4',
    appId: '1:892907522158:ios:61e418474a30a9a3ee7e7f',
    messagingSenderId: '892907522158',
    projectId: 'smartsproutadmin',
    storageBucket: 'smartsproutadmin.firebasestorage.app',
    iosBundleId: 'com.example.smartsprout',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBDzZUgozsBsRQ8K--dtMur5Cz4s1Zr1f4',
    appId: '1:892907522158:ios:61e418474a30a9a3ee7e7f',
    messagingSenderId: '892907522158',
    projectId: 'smartsproutadmin',
    storageBucket: 'smartsproutadmin.firebasestorage.app',
    iosBundleId: 'com.example.smartsprout',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC5N23TZp-uKGZWsQeIf5bT1cAONAFPoRo',
    appId: '1:892907522158:web:329f72271e428674ee7e7f',
    messagingSenderId: '892907522158',
    projectId: 'smartsproutadmin',
    authDomain: 'smartsproutadmin.firebaseapp.com',
    storageBucket: 'smartsproutadmin.firebasestorage.app',
    measurementId: 'G-XYBZ1204C7',
  );
}